openapi: 3.0.3
info:
  title: User and Agenda Source Management API
  description: API for managing users and their agenda sources.
  version: 1.1.0

paths:
  /api/register:
    post:
      summary: Register a new user
      description: Registers a new user by accepting email and password.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  example: user@example.com
                password:
                  type: string
                  format: password
                  example: StrongPass!123
              required:
                - email
                - password
      responses:
        '201':
          description: User registered successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid input or email already exists
        '422':
          description: Password does not meet complexity requirements
        '500':
          description: Internal server error

  /api/users/{id}:
    put:
      summary: Update a user's account details
      security:
        - BearerAuth: [ ]
      description: Updates the email and/or password for the user specified by the `id`.
      parameters:
        - name: id
          in: path
          description: The unique identifier (UUID) of the user
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  example: newemail@example.com
                password:
                  type: string
                  format: password
                  example: NewPass123!
              required: []
      responses:
        '200':
          description: User updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid input or UUID
        '404':
          description: User not found
        '500':
          description: Internal server error

  /api/agenda-sources:
    get:
      summary: Get a list of agenda sources
      security:
        - BearerAuth: [ ]
      description: Retrieves a list of all agenda sources. Supports ordering by `updatedAt` and pagination.
      parameters:
        - name: orderBy
          in: query
          description: Order the results by `updatedAt` in ascending (`asc`) or descending (`desc`) order.
          required: false
          schema:
            type: string
            enum:
              - asc
              - desc
            default: asc
        - name: page
          in: query
          description: The page number to retrieve (1-based).
          required: false
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: pageSize
          in: query
          description: The number of items to include per page.
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
      responses:
        '200':
          description: List of agenda sources retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/AgendaSource'
                  pagination:
                    $ref: '#/components/schemas/Pagination'
        '500':
          description: Internal server error
    post:
      summary: Create a new agenda source
      security:
        - BearerAuth: [ ]
      description: Creates a new agenda source with a URL and type.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                  format: uri
                  example: https://example.com/calendar
                type:
                  type: string
                  enum:
                    - proton
                  example: proton
              required:
                - url
                - type
      responses:
        '201':
          description: Agenda source created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AgendaSource'
        '400':
          description: Invalid input
        '500':
          description: Internal server error

  /api/agenda-sources/{id}:
    get:
      summary: Get an agenda source by ID
      security:
        - BearerAuth: [ ]
      description: Retrieves an agenda source by its unique identifier.
      parameters:
        - name: id
          in: path
          description: The unique identifier (UUID) of the agenda source
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Agenda source retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AgendaSource'
        '404':
          description: Agenda source not found
        '500':
          description: Internal server error

    put:
      summary: Update an agenda source by ID
      security:
        - BearerAuth: [ ]
      description: Updates the URL and/or type of an agenda source by its unique identifier.
      parameters:
        - name: id
          in: path
          description: The unique identifier (UUID) of the agenda source
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                  format: uri
                  example: https://newexample.com/calendar
                type:
                  type: string
                  enum:
                    - proton
                  example: proton
              required: []
      responses:
        '200':
          description: Agenda source updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AgendaSource'
        '400':
          description: Invalid input or UUID
        '404':
          description: Agenda source not found
        '500':
          description: Internal server error

    delete:
      summary: Delete an agenda source by ID
      security:
        - BearerAuth: [ ]
      description: Deletes an agenda source by its unique identifier.
      parameters:
        - name: id
          in: path
          description: The unique identifier (UUID) of the agenda source
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Agenda source deleted successfully
        '404':
          description: Agenda source not found
        '500':
          description: Internal server error

  /api/agenda-items:
    post:
      security:
        - BearerAuth: [ ]
      summary: Create or update multiple agenda items
      description: Accepts multiple AgendaItem objects and creates or updates them.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/AgendaItem'
      responses:
        '200':
          description: Agenda items processed successfully
        '400':
          description: Invalid input
        '500':
          description: Internal server error

    get:
      security:
        - BearerAuth: [ ]
      summary: Query agenda items
      description: Retrieves agenda items based on query parameters.
      parameters:
        - name: agendaSourceID
          in: query
          schema:
            type: string
            format: uuid
        - name: userID
          in: query
          schema:
            type: string
            format: uuid
        - name: startTime
          in: query
          schema:
            type: string
            format: date-time
        - name: endTime
          in: query
          schema:
            type: string
            format: date-time
        - name: page
          in: query
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: pageSize
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
      responses:
        '200':
          description: Paginated list of agenda items
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/AgendaItem'
                  pagination:
                    $ref: '#/components/schemas/Pagination'
        '500':
          description: Internal server error

  /api/agenda-items/{id}:
    get:
      security:
        - BearerAuth: [ ]
      summary: Get an agenda item by ID
      description: Retrieves an agenda item by its ResourceID.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Agenda item retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AgendaItem'
        '404':
          description: Agenda item not found
        '500':
          description: Internal server error
    delete:
      security:
        - BearerAuth: [ ]
      summary: Delete one or multiple agenda items
      description: Deletes agenda items by their ResourceIDs.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Agenda items deleted successfully
        '400':
          description: Invalid input
        '500':
          description: Internal server error

  /api/agenda-invites:
    post:
      security:
        - BearerAuth: [ ]
      summary: Create a new agenda invite
      description: Creates a new AgendaInvite.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AgendaInvite'
      responses:
        '201':
          description: Agenda invite created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AgendaInvite'
        '400':
          description: Invalid input
        '500':
          description: Internal server error

  /api/agenda-invites/{id}:
    get:
      security:
        - BearerAuth: [ ]
      summary: Get an agenda invite by ID
      description: Retrieves an AgendaInvite by its ResourceID.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Agenda invite retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AgendaInvite'
        '404':
          description: Agenda invite not found
        '500':
          description: Internal server error

    put:
      security:
        - BearerAuth: [ ]
      summary: Update an agenda invite by ID
      description: Updates an AgendaInvite by its ResourceID.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AgendaInvite'
      responses:
        '200':
          description: Agenda invite updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AgendaInvite'
        '400':
          description: Invalid input or UUID
        '404':
          description: Agenda invite not found
        '500':
          description: Internal server error

    delete:
      security:
        - BearerAuth: [ ]
      summary: Delete an agenda invite by ID
      description: Deletes an AgendaInvite by its ResourceID.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Agenda invite deleted successfully
        '404':
          description: Agenda invite not found
        '500':
          description: Internal server error
  /api/view-agenda-invite/{id}:
    get:
      summary: Publicly available view of a user agenda.
      description: Retrieves a list of AgendaItemViews for the specified invite ID within the given date range.
      parameters:
        - name: id
          in: path
          description: The unique identifier (UUID) of the agenda invite
          required: true
          schema:
            type: string
            format: uuid
        - name: DateFrom
          in: query
          description: The start date and time for filtering agenda items
          required: false
          schema:
            type: string
            format: date-time
        - name: DateTo
          in: query
          description: The end date and time for filtering agenda items
          required: false
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: List of AgendaItemViews retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AgendaItemView'
        '404':
          description: Agenda invite not found
        '500':
          description: Internal server error

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT # Optional: Specify token format

  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: The unique identifier of the user
          example: "f47ac10b-58cc-4372-a567-0e02b2c3d479"
        email:
          type: string
          format: email
          description: The user's email address
          example: user@example.com
        createdAt:
          type: string
          format: date-time
          description: The time when the user was created
          example: "2023-12-01T12:00:00Z"
        updatedAt:
          type: string
          format: date-time
          description: The last time the user's details were updated
          example: "2023-12-02T15:00:00Z"
      required:
        - id
        - email

    AgendaSource:
      type: object
      description: "Agenda source to fetch agenda items from"
      properties:
        id:
          type: string
          format: uuid
          description: The unique identifier of the agenda source
          example: "c29ac10b-58cc-4372-a567-0e02b2c3d479"
        url:
          type: string
          format: uri
          description: The URL of the agenda source
          example: https://example.com/calendar
        type:
          type: string
          enum:
            - proton
          description: The type of the agenda source
          example: proton
        userId:
          type: integer
          format: uuid
          description: The ID of the user who owns the agenda source
          example: "f47ac10b-58cc-4372-a567-0e02b2c3d479"
        createdAt:
          type: string
          format: date-time
          description: The time when the agenda source was created
          example: "2023-12-01T12:00:00Z"
        updatedAt:
          type: string
          format: date-time
          description: The last time the agenda source was updated
          example: "2023-12-02T15:00:00Z"
      required:
        - id
        - url
        - type
    AgendaItem:
      type: object
      properties:
        ResourceID:
          type: string
          format: uuid
          description: The unique identifier of the agenda item
        StartTime:
          type: string
          format: date-time
        EndTime:
          type: string
          format: date-time
        Description:
          type: string
        AgendaSourceID:
          type: string
          format: uuid
        UserID:
          type: string
          format: uuid
    AgendaInvite:
      type: object
      properties:
        ResourceID:
          type: string
          format: uuid
          description: The unique identifier of the agenda invite
        UserID:
          type: string
          format: uuid
          description: The ID of the user associated with the invite
        Description:
          type: string
        ExpiresAt:
          type: string
          format: date-time
        NotBefore:
          type: string
          format: date-time
        NotAfter:
          type: string
          format: date-time
        PaddingBefore:
          type: string
          description: Duration before the event
        PaddingAfter:
          type: string
          description: Duration after the event
        SlotSizes:
          type: array
          items:
            type: string
          description: Array of slot sizes as durations
        AgendaSources:
          type: array
          items:
            $ref: '#/components/schemas/AgendaSource'
#        ProceduralAgendas:
#          type: array
#          items:
#            $ref: '#/components/schemas/ProceduralAgenda'
    Pagination:
      type: object
      properties:
        page:
          type: integer
          description: The current page number.
          example: 1
        pageSize:
          type: integer
          description: The number of items per page.
          example: 20
        totalItems:
          type: integer
          description: The total number of items available.
          example: 123
        totalPages:
          type: integer
          description: The total number of pages available.
          example: 7

    AgendaItemView:
      description: "A view of an agenda item, which 
      does not include sensitive data about the user."
      type: object
      properties:
        StartTime:
          type: string
          format: date-time
        EndTime:
          type: string
          format: date-time
        Description:
          type: string